Add pagination in react table
leapfrogtechnology/reactjs-starter pull request #35
Opened 2020-05-11 04:36 UTC by bipulthapa

- Add pagination from server site with correct limit and page number
- Add pagination in the employee list page
- Add data to JSON mock server db.json

2020-05-13 11:35 UTC, sanjevShakya requested changes

2020-05-13 11:35 UTC, sanjevShakya commented on src/components/common/pagination/Pagination.js
> +import _ from 'lodash';
I see that you've used lodash range function. Can you research on why we should not import entire lodash?
And then change this to 
```javascript
import _range from 'lodash/range';
```

2020-05-13 11:35 UTC, sanjevShakya commented on src/components/common/pagination/Pagination.js
> +  state = { visiblePages: [] };
we have a convention to add the state inside the constructor function

2020-05-13 11:35 UTC, sanjevShakya commented on src/components/common/pagination/Pagination.js
> +  componentWillReceiveProps(nextProps) {
the method is deprecated and we should use ```getDerivedStateFromProps```

2020-05-13 11:37 UTC, sanjevShakya commented
We have redux setup in the project. Shouldn't we used flux architecture for our data management?
@pratishshr can you add something to this.

2020-05-14 03:27 UTC, bipulthapa commented on src/components/common/pagination/Pagination.js
> +import _ from 'lodash';
For the sake of optimization, we should not import the entire lodash. Using specific imports will reduce the bundle size. Thank you dai for pinpointing it

2020-05-14 03:29 UTC, bipulthapa commented on src/components/common/pagination/Pagination.js
> +  componentWillReceiveProps(nextProps) {
In the latest change, I have use componentDidUpdate. Hope this is also a good practice

2022-06-08 16:19 UTC, bikkimahato commented on src/components/common/pagination/Pagination.js
> +    if (prevProps.pages != pages) {
Please use strict inequality operator !==

2022-07-25 08:56 UTC, closed without merging